### ISSUE TITLE
Issue while giving empty value for long_read_rna_pipeline.variants

### ISSUE THREAD

**Issue by likhitha-surapaneni** [ENCODE-DCC/long-read-rna-pipeline#71]
Hi,

I tried running the pipeline using `test/test_workflow/json/test_workflow_input.json` but with empty value for long_read_rna_pipeline.variants and it is failing with the error "Could not localize: File name too long" for call-transcriptclean.  When the value is empty, it seems to be localizing the directory from which the pipeline was started. Can you help us in understanding how localization works for empty input `File?` strings?

Can you also let us know if empty values are permitted for long_read_rna_pipeline.variants ?

Thank you for your time!

**Comment by ottojolanki** [comment]
Hi, and thank you for your interest in the pipeline. Any input that has a `?` after the type is optional, and can be left undefined (empty). Could you provide me with couple of bits of extra information so I could better understand the problem? I would like to know your Operating System, Docker version, caper version and Cromwell version and the full command line you are starting the pipeline run with.

**Comment by likhitha-surapaneni** [comment]
Hi, 

Please find the following details:

Operating system: CentOS Linux 3.10.0-1062.18.1.el7.x86_64
Backend: SLURM 
Package management for tools: Each tool used in the pipeline is installed separately and loaded to the environment using environment modules
Caper version: 1.6.3
Cromwell version: 59

I am using caper server-client mode to run the pipeline: `caper submit long-read-rna-pipeline.wdl -i test/test_workflow/json/test_workflow_input.json`

Update: Instead of giving empty string for long_read_rna_pipeline.variants, omitting the line from test_workflow_input.json seems to be doing the trick. Kindly let me know if this is the excepted behaviour

Thank you for your patience!

**Comment by ottojolanki** [comment]
Ok, thanks. Yes, for optional inputs (the ones with `?`) you should omit the input altogether. You are doing it right.
