### ISSUE TITLE
JSON file - small, medium , large, xlarge task resources ?

### ISSUE THREAD

**Issue by PriyamvadaKumar** [ENCODE-DCC/long-read-rna-pipeline#72]
what are the small, medium , large and xlarge task resources and how are they using CPU and memory in processing ?

**Comment by ottojolanki** [comment]
Hi, and thank you for the interest in the pipeline! The default resource classes are:
```       
        Resources small_task_resources = {
           "cpu": 2,
           "memory_gb": 7,
           "disks": "local-disk 50 SSD",
        }
        Resources medium_task_resources = {
           "cpu": 6,
           "memory_gb": 32,
           "disks": "local-disk 100 SSD",
        }
        Resources large_task_resources = {
           "cpu": 16,
           "memory_gb": 60,
           "disks": "local-disk 150 SSD",
        }
        Resources xlarge_task_resources = {
           "cpu": 20,
           "memory_gb": 120,
           "disks": "local-disk 150 SSD",
        }
```
Memory and disk are both gigabytes. The defaults are somewhat optimized for processing speed. You can override these in your input `json`. For an example of how to override, see https://github.com/ENCODE-DCC/long-read-rna-pipeline/blob/dev/test/test_workflow/json/test_workflow_input.json
